name: test.yml
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  ruff:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version-file: ".python-version"

      - name: Install dependencies
        run: pip3 install ruff

      - name: Run ruff
        run: ruff check --output-format=github .

  mypy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version-file: ".python-version"

      - name: Install dependencies
        run: pip3 install mypy

      - name: Run mypy
        run: mypy .
        continue-on-error: true

  unit-tests:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: [ 3.11, 3.12, 3.13 ]
        pandas-version: [ 2.2.3, ]
        pydantic-version: [ 2.6.0, 2.11.4 ]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: { { matrix.python-version } }

      - name: Install dependencies
        run: pip3 install pandas=={{ matrix.pandas-version }} pydantic=={{ matrix.pydantic-version }} pytest pytest-cov

      - name: Run unit-tests
        run: pytest . -vv

      - name: Get Cover
        uses: orgoro/coverage@v3.2
        with:
          coverageFile: coverage.xml
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: PR metrics
        uses: microsoft/PR-Metrics@v1.6.5
        env:
          PR_METRICS_ACCESS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        continue-on-error: true
